name: Master branch
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest

    steps:
      - name: Attach repository
        uses: actions/checkout@v1

      - run: echo $GITHUB_WORKSPACE
      - run: echo ${GITHUB_WORKSPACE}
      
      - name: Add variables to environment 
        run: |
          echo "::set-env name=PACKAGE_VERSION::$(node -v)"
          echo "::set-env name=LABEL::${GITHUB_RUN_ID}-v${PACKAGE_VERSION}-${GITHUB_SHA}"
          echo "::set-env name=ZIP_LABEL::v${PACKAGE_VERSION}_${GITHUB_SHA}"
          echo "::set-env name=WA_ACCOUNT_PACKAGE_VERSION::$(npm -v)-$PACKAGE_VERSION"
      - name: tets availability
        run: |
          echo $PACKAGE_VERSION
          echo $LABEL
          echo $ZIP_LABEL
          echo $WA_ACCOUNT_PACKAGE_VERSION

  build2:  
    name: Building2
    runs-on: ubuntu-latest

    steps:  
      - run: |
          echo $PACKAGE_VERSION
          echo $LABEL
          echo $ZIP_LABEL
          echo $WA_ACCOUNT_PACKAGE_VERSION
